name: plantable
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  device_preview: ^1.0.0
  dio: ^4.0.4
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  responsive_framework: ^0.1.5
  get_cli: ^1.7.1
  fancy_bottom_navigation: ^0.3.3
  bulleted_list: ^0.0.1+0.1a
  percent_indicator: ^4.0.0
  
  flutter: 
    sdk: flutter
  
  
dev_dependencies: 
  flutter_lints: ^1.0.0

  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/